// src/ai/dev.ts
import '@/ai/flows/personalized-insights';
import '@/ai/flows/moderate-community-post-flow'; 
import '@/ai/flows/recommended-content';
import '@/ai/flows/task-suggestions';
import '@/ai/tools/calculate-reward-points';
import '@/ai/flows/community-challenges-flow'; 
import '@/ai/flows/generate-avatar-flow';
import '@/ai/flows/validate-avatar-description-flow'; 
